---
apiVersion: v1
kind: Service
metadata:
  name: hours-service
  labels:
    app: hayshours
spec:
  type: NodePort
  selector:
    app: hayshours
  ports:
    - protocol: "TCP"
      port: 8989
      targetPort: 5000
      nodePort: 30036
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hayshours
  labels:
    app: hayshours
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hayshours
  template:
    metadata:
      annotations:
        hayshoursrpi/change-cause: "Use multi-stage build version 1"
      labels:
        app: hayshours
    spec:
      containers:
        - name: hayshours
          image: gaillardo/hayshoursrpi:small-alpine-sql-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
