FROM golang:alpine AS pylib-image
RUN apk update && apk add bash python3
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY requirements_file.txt ./requirements.txt
RUN python3 -m venv $VIRTUAL_ENV && \
	pip3 install --upgrade pip && \
    	pip3 install -r requirements.txt

FROM golang:alpine AS build-image
RUN apk update && apk add bash python3
RUN mkdir -p /app/python/test /app/python/templates
COPY python/ /app/python/
COPY --from=pylib-image /opt/venv /opt/venv
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV STATEFUL_TYPE=FILE
WORKDIR /app
EXPOSE 5000
CMD ["python", "/app/python/server.py"]
