FROM amd64/alpine
RUN apk update && apk add bash \
&& apk add python3 \
&& apk add py3-pip \
&& pip3 install flask
ENV ROOTDIR=/var/lib/data
RUN mkdir /var/lib/data
RUN mkdir /app
RUN mkdir /app/templates
ADD templates /app/templates
ADD hayshours.py /app
ADD server.py /app
ADD persist.py /app
WORKDIR /app
EXPOSE 5000
CMD ["python3", "/app/server.py"]
