---
apiVersion: v1
kind: Service
metadata:
  name: hours-dataservice
  labels:
    app: hoursdata
spec:
  type: NodePort
  selector:
    app: hoursdata
  ports:
    - protocol: "TCP"
      port: 8989
      name: oli
      targetPort: 5000
      nodePort: 30037
---
apiVersion: v1
kind: Pod
metadata:
  name: hoursdata-pod
  labels:
    app: hoursdata
spec:
  volumes:
  - name: hours-data
    hostPath:
      path: "/var/lib/data"
      type: Directory
  containers:
  - name: hoursdata
    image: gaillardo/hayshoursrpi:datavol
    imagePullPolicy: Always
    volumeMounts:
      - name: "hours-data"
      - mountPath: "/data"
      ports:
        - containerPort: 5000
