---
apiVersion: v1
kind: Pod
metadata:
  name: hoursdata-pod
  labels:
    app: hoursdata
spec:
  volumes:
  - name: hours-data
    hostPath:
      path: /home/ubuntu
      type: Directory
  containers:
  - image: gaillardo/hayshoursrpi:datavol
    imagePullPolicy: Always
    name: hoursdata
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: /data
      name: hours-data
