---
apiVersion: v1
kind: Service
metadata:
  name: hours-service
  labels:
    app: hayshours
spec:
  type: NodePort
  selector:
    app: hayshours
  ports:
    - protocol: "TCP"
      port: 8989
      name: oli
      targetPort: 5000
      nodePort: 30036
---
apiVersion: v1
kind: Pod
metadata:
  name: hayshours
  labels:
    app: hayshours
spec:
  volumes:
  - name: hours-data
    hostPath:
      path: "/var/lib/data"
      type: Directory
  containers:
  - name: hayshours
    image: gaillardo/hayshoursrpi:datavol
    imagePullPolicy: Always
    volumeMounts:
      - name: "hours-data"
      - mountPath: "/data"
      ports:
        - containerPort: 5000
