---
apiVersion: v1
kind: Service
metadata:
  name: hours-service
  labels:
    run: hours-service
spec:
  type: NodePort
  selector:
    app: hoursdata
  ports:
    - protocol: "TCP"
      port: 8999
      name: hours
      targetPort: 5000
      nodePort: 30038
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoursdata-deploy
  labels:
    app: hoursdata
spec:
  selector:
    matchLabels:
      run: hoursdata
  replicas: 1
  template:
    metadata:
      labels:
        run: hoursdata
    spec:
      volumes:
        - name: hours-data
          hostPath:
            path: /home/ubuntu/hoursdata # this dir should exist on node
            type: Directory
      containers:
      - name: hoursdata
        image: gaillardo/hayshoursrpi:datavol
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /data
          name: hours-data
