---
apiVersion: v1
kind: Service
metadata:
  name: hours-service-file
  labels:
    run: hours-service-file
spec:
  type: NodePort
  selector:
    run: hoursdata-file
  ports:
    - protocol: "TCP"
      port: 8999
      name: hours
      targetPort: 5000
      nodePort: 30038
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoursdata-deploy
  labels:
    run: hoursdata-file
spec:
  selector:
    matchLabels:
      run: hoursdata-file
  replicas: 1
  template:
    metadata:
      annotations:
        hayshourrpi-file/change-cause: "fix LF bug and refactor"
      labels:
        run: hoursdata-file
    spec:
      volumes:
        - name: hours-data
          hostPath:
            path: /home/ubuntu/hoursdata # this dir should exist on node
            type: Directory
      containers:
      - name: hoursdata
        image: gaillardo/hayshoursrpi:file-v3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /data
          name: hours-data
