---
apiVersion: v1
kind: Service
metadata:
  name: hours-service
  labels:
    app: hayshours
spec:
  type: NodePort
  selector:
    app: hayshours
  ports:
    - protocol: "TCP"
      port: 8989
      name: oli
      targetPort: 5000
      nodePort: 30036
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hayshours
  labels:
    app: hayshours
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hayshours
  template:
    metadata:
      labels:
        app: hayshours
    spec:
      volumes:
        - name: "hours-data"
        hostPath:
          path: "/var/lib/data"
      containers:
        - name: hayshours
          image: gaillardo/hayshoursrpi:datavol
          volumeMounts:
            - mountPath: "/data"
            - name: "hours-data"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
